Repository cedricpinson/osgjs, pull requests merged in 2018-03, with the labels that each got.

#956 Fixes mouse wheel issues
  sources/osgGA/FirstPersonManipulatorStandardMouseKeyboardController.js
  sources/osgViewer/input/source/InputSourceMouse.js
Labels: Needs review

#957 Fixes crash with IE 11 on Inputmanager Initialization
  sources/osg/polyfill.js
  sources/osgViewer/input/source/InputSourceKeyboard.js
Labels: Needs merge

#958 Removes unnecessary closure with early return
  sources/osg/polyfill.js
Labels: Needs review

#959 Fixes shader error handling when spector enabled
  sources/osg/Program.js
Labels: Needs review

#960 Fixes wrong worldFactor parameter usage
  sources/osgGA/FirstPersonManipulatorWebVRController.js
  sources/osgGA/OrbitManipulatorWebVRController.js
  sources/osgViewer/input/source/InputSourceWebVR.js
Labels: Needs merge

#961 Fixes manipulator setup in animate rotation tutorial
  examples/animate-rotation/main.js
Labels: Needs review

#962 Fixes wrong call to unzip
  sources/osgPlugins/ReaderWriterZIP.js
Labels: Needs review

#963 Fixes error throwing case and reporting of input error
  sources/osgViewer/input/source/InputSourceKeyboard.js
Labels: Needs merge, Needs review

#964 Fixes stringify with circular references
  sources/osgViewer/input/source/InputSourceKeyboard.js
Labels: Needs merge, Needs review

#965 Catches promise Error on pollheadsets
  sources/osgViewer/input/source/InputSource.js
  sources/osgViewer/input/source/InputSourceWebVR.js
Labels: Needs review
